### ISSUE TITLE
Container Image Security Vulnerabilities

### ISSUE THREAD

**Issue by bostrowski13** [snowplow/stream-collector#150]
Curernt Kinesis Image in dockerhub (snowplow/scala-stream-collector-kinesis) has 17 High Vulnerabilities, and a total of 75.  The image itself is 8 days old, but the base image is 2+ months old.  

Is security scanning included in the build of these and are there plans to address these any time soon?

**Comment by dilyand** [comment]
Hey @bostrowski13 , yes, security scanning is [part](https://github.com/snowplow/stream-collector/runs/2665734927?check_suite_focus=true) of the CI/CD pipeline for this project.

We actively scan for issues and triage and fix those we think present an active concern to the user. 

As you point out, the culprit is the base image. In this project, we make fixing vulnerabilities that arise from the collector's dependencies the priority. The base image is maintained [elsewhere](https://github.com/snowplow/snowplow-docker).

I will close this issue but do get in touch if you have any concerns.
