### ISSUE TITLE
Update /sink-health endpoint logic

### ISSUE THREAD

**Issue by ianarsenault** [snowplow/stream-collector#276]
Currently the collector's `/sink-health` endpoint returns with a 200 response immediately upon startup, even if there's an ongoing outage or there are no sinks available with `ResourceNotFoundException` errors. It isn't until after multiple retries, that the endpoint is updated to 503 service unavailable.  

An example I've seen is collectors would start up with `/sink-health` as "healthy" then take 5-10 minutes to become unhealthy after retrying 3 times (with length in between retries depending on backoff). This is not correct from a standpoint of failover, as a health check endpoint should start out unhealthy until proven to be healthy (sinks exist and are available / no outage)

In my testing of using `/sink-health` as a health check for target group I've noticed two areas of concern

1. If traffic spike causes scaling action during an outage -> new collectors that start up `/sink-health` will return 200 until they are updated to be unhealthy after multiple retries (from outage or non-existent resource) - If there's logic based on `/sink-health` to handle failover to set of healthy collectors - this will cause events to be sent to a collector experiencing an outage 
2. During an outage -> Collector services could fall into potential restart loop due to memory or cpu circuit breaks -> causing node’s collector service to restart ->  making it so upon restart `/sink-health` returns healthy/200 and begins taking traffic -> does multiple retries after some time -> updates to 503/unhealthy 

A small snippet of logs show that upon startup there's errors writing but `/sink-health` will return 200 until retries complete
```
NOTE: Picked up JDK_JAVA_OPTIONS: -Dlog4j2.formatMsgNoLookups=true -Xms2g -Xmx2g -Dorg.slf4j.simpleLogger.defaultLogLevel=warn 
--
[pool-1-thread-4] ERROR com.snowplowanalytics.snowplow.collectors.scalastream.sinks.KinesisSink - Writing failed with error:
com.amazonaws.services.kinesis.model.ResourceNotFoundException: Stream collector-raw-stream under account <account_id> not found. (Service: AmazonKinesis; Status Code: 400; Error Code: ResourceNotFoundException; Request ID: c6a451c3-6d25-323f-9a9f-9517f28eea7d; Proxy: null)
[pool-1-thread-4] ERROR com.snowplowanalytics.snowplow.collectors.scalastream.sinks.KinesisSink - Retrying writing batch to Kinesis stream collector-raw-stream in 3000 milliseconds...
--
[pool-1-thread-8] ERROR com.snowplowanalytics.snowplow.collectors.scalastream.sinks.KinesisSink - Writing failed with error:
com.amazonaws.services.kinesis.model.ResourceNotFoundException: Stream collector-raw-stream under account <account_id> not found. (Service: AmazonKinesis; Status Code: 400; Error Code: ResourceNotFoundException; Request ID: d0445364-ab6d-0162-8c7f-97b07f3deb2b; Proxy: null)
````

If `/sink-health` endpoint is being used as a means for failing over to healthy collector alb/region then this poses an issue, as collectors that startup during an outage could lead to potential data loss if surge protection is not enabled or if there's a Kinesis + SQS outage

Suggested improvements
- The isHealthy override flag for `/sink-health` in [Kinesis](https://github.com/snowplow/stream-collector/blob/master/kinesis/src/main/scala/com.snowplowanalytics.snowplow.collectors.scalastream/sinks/KinesisSink.scala#L89-L90) and [SQS](https://github.com/snowplow/stream-collector/blob/master/sqs/src/main/scala/com.snowplowanalytics.snowplow.collectors.scalastream/sinks/SqsSink.scala#L75-L76) should be updated to start out as false
- Logic should be added for [the /sink-health endpoint](https://github.com/snowplow/stream-collector/blob/master/core/src/main/scala/com.snowplowanalytics.snowplow.collectors.scalastream/CollectorRoute.scala#L178-L188) in the same manner as [/health](https://github.com/snowplow/stream-collector/commit/96d2433dcb173ee4511361cc25b05b637c2bdd1d) where it's not made "healthy" until it's verified the sinks exist (no 400 - ResourceNotFoundException errors) and there's no outage from AWS (5xx)
- Log some informational message when there's a sink outage and `/sink-health` is unhealthy for a given collector

**Comment by dilyand** [comment]
Hi @ianarsenault , that all sounds reasonable. I just have one aspect I'm unsure of: how is any downstream logic going to know when a collector is genuinely unhealthy and when it's still in a 'just started, don't know yet' state? Maybe a specialised response code would be a better choice instead of reusing the 503?

On the flip side, adding a custom response complicates things -- is it justified in this case?

**Comment by ianarsenault** [comment]
hey @dilyand , I am not sure a custom response is needed in this case, just that `/sink-health` should return 503 service unavailable until it's verified sinks are healthy on startup.

**Comment by dilyand** [comment]
@ianarsenault , maybe I'm thinking about it the wrong way but...

Any alerting or mitigation off the `/sink-health` endpoint would be triggered by a 503. Do we want that in case the sink is not really unhealthy but simply just not proven healthy yet?

Of course, we can have a timeout, eg 'only alert / mitigate' after X secs of 503s. But that is the exact behaviour we already have: where downstream nothing happens for some time, until the unhealthiness is established.

**Comment by ianarsenault** [comment]
@dilyand alerting due to 503 on startup should only happen on initial deployment of collectors (expected), or when all collectors `/sink-health` are returning 503 (considered an outage).

If we have a pool of collectors and a new one is added with it's `/sink-health` returning 503  on startup-> no traffic would be routed to it until it's healthy and no alerts should fire as those would be set at the collector load balancer level. 

From a high level something like this 

```mermaid
flowchart TD
    A[Collector Deployed] -->|/sink-health = 503| B{Collector Verifies Sinks}
    B -->|sinks are healthy| C[ update /sink-health = 200 ]
    B -->|ongoing outage| D[ /sink-health remains unhealthy ]
    D -->|retry verification| B
```

Currently testing out [this change](https://github.com/snowplow/stream-collector/commit/e1c3112399b178df896a726d73ad4770340776e0) in various scenarios to see if this will work

**Comment by benjben** [comment]
The logic for `/sink-health` will be updated for these assets:
- PubSub
- Kinesis and Kinesis + SQS (same asset)
- SQS

Below is the list of changes.

#### 1. Making `/sink-health` endpoint healthy after start-up

Collector starts with `/sink-health` endpoint unhealthy (`503`), until proven healthy.

- Kinesis: in the background, the collector repeatedly (every second) queries `describeStreamSummary`. When the status of both good and bad streams is `ACTIVE`, `/sink-health` becomes healthy.
At the moment [Enrich](https://github.com/snowplow/enrich/blob/3.7.0/modules/kinesis/src/main/scala/com/snowplowanalytics/snowplow/enrich/kinesis/Sink.scala#L90) and [collector](https://github.com/snowplow/stream-collector/blob/2.8.2/kinesis/src/main/scala/com.snowplowanalytics.snowplow.collectors.scalastream/sinks/KinesisSink.scala#L529) both use `describeStream`, which [has a limit](https://docs.aws.amazon.com/streams/latest/dev/service-sizes-and-limits.html) of 10 calls per second per account. `describeStreamSummary` has a limit of 20 calls per second per account, so it’ll be possible to do more, and they won’t compete with Enrich.
There are good chances that `LimitExceededException` will be hit (cf [#174](https://github.com/snowplow/stream-collector/issues/174)). This is fine with a retry every second. 20 calls can be successful per second, and there will be 20 less calls each second, so starting 100 collectors at once it’d take less than a minute.

- SQS: in the background, the collector repeatedly queries `getQueueUrl` until it gets a result for both streams.

- Kinesis + SQS: endpoint becomes healthy when either Kinesis or SQS becomes healthy, because it means that the collector can write the events somewhere already and does not keep them in-memory.

- PubSub: in the background, the collector repeatedly queries `listTopics` until it can see both streams.

It’s important to keep in mind that this will run in the background when the collector starts, but the collector will be able to receive events already and try to write them to the sinks even if the above tests are not successful yet. Also, if writing to good and bad sinks succeeds before the above tests, `/sink-health` will become healthy and the background tests will stop.

This will be the default and only behavior, as this is non-blocking. So [enableStartupChecks](https://github.com/snowplow/stream-collector/blob/2.8.2/core/src/main/scala/com.snowplowanalytics.snowplow.collectors.scalastream/model.scala#L214), which would prevent the collector from starting if the streams do not exist (blocking), will be removed.

#### 2. Making /health-endpoint unhealthy during processing

- Kinesis + SQS : at the moment, *each* batch of events is *first* tried to be written to Kinesis and if it fails `MaxRetries` times *then* to SQS. It means that in case of Kinesis outage, all the batches are first tried to be written to Kinesis.
The behavior will be updated to this: as soon as one batch fails `MaxRetries` times to be written to Kinesis, the collector is switched to write all subsequent batches to SQS. In parallel in the background the status of Kinesis is checked every second (with `describeStreamSummary`, like at startup) and when it's `ACTIVE` again, the collector is switched back to Kinesis.
If `MaxRetries` attempts to write a batch to SQS fail, then `/sink-health` is made unhealthy, until it succeeds.
